version = 0.1

[default.build.parameters]
cached = true
parallel = true

# sam deploy --config-env dev  (JwtSecret is passed on the first deploy via
# --parameter-overrides and reused from the stack afterwards)
[dev.deploy.parameters]
stack_name = "tinyprotocol-dev"
resolve_s3 = true
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "Stage=\"dev\" MyChartRedirectUrl=\"https://z7yrwag4b4.execute-api.us-east-1.amazonaws.com/v1/mychart/callback\" MyChartClientId=\"16d993cb-326e-4e63-bf69-ea37a1da6369\""

[prod.deploy.parameters]
stack_name = "tinyprotocol-prod"
resolve_s3 = true
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
parameter_overrides = "Stage=\"prod\""
